id: AA68D165A
title: Aspiration Prayer
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:00:26.070708
  last_modified_at: 2022-03-01 02:00:26.070715
